<?php
/**
 * @file
 * Code for the Dennis Client feature.
 */

include_once 'dennis_client.features.inc';
/**
 * @file
 * Code for the Dennis Client module.
 */

/**
 * Implements hook_dfp_global_targeting_alter().
 *
 * Adjust the ad tags if the current node, index page is tagged with a
 * "client" taxonomy term.
 * @see https://didev.fogbugz.com/default.asp?20972
 * @see https://didev.fogbugz.com/default.asp?23527
 */
function dennis_client_dfp_global_targeting_alter(&$targeting) {

  // Start point for the $client_page variable.
  $client_page = FALSE;
  $whitelist = array(
    'article',
    'ord',
    'test',
    'live',
  );

  // Get the current page object.
  $item = menu_get_object();

  // Check for a node with content in field_client.
  if ($item && $item->nid && !empty($item->field_client)) {
    if (!empty($item->field_client[LANGUAGE_NONE][0]['taxonomy_term'])) {
      // Use the already loaded term.
      $term = $item->field_client[LANGUAGE_NONE][0]['taxonomy_term'];
    }
    else {
      // Load the term.
      if (isset($item->field_client[LANGUAGE_NONE])) {
        $term = taxonomy_term_load($item->field_client[LANGUAGE_NONE][0]['tid']);
      }
      else {
        $term = FALSE;
      }
    }

    // Sanity check, can't do proper object instance checking in Drupal 7.
    if (!$term) {
      return;
    }

    // Ensure we a referring to our 'client' taxonomy.
    if ($term->vocabulary_machine_name != 'clients') {
      return;
    }

    $client_page = TRUE;
  }
  else {
    // Get the current page object.
    $menu_item = menu_get_item();

    // Add the client key value pair on index pages.
    if (strpos($menu_item['path'], 'taxonomy/term/') !== FALSE && !empty($menu_item['page_arguments'][0])) {
      $term = taxonomy_term_load($menu_item['page_arguments'][0]);
      if (isset($term->vocabulary_machine_name) && $term->vocabulary_machine_name == 'clients') {
        $client_page = TRUE;
      }
    }
  }

  // Check for whitelisted keys and add the client kvp.
  if ($client_page) {

    foreach ($targeting as $index => $entry) {
      if (!in_array($entry['target'], $whitelist)) {
        unset($targeting[$index]);
      }
    }

    $targeting[] = array(
      'target' => 'client',
      'value' => taxonomy_term_title($term),
    );
  }
}

/**
 * Ensures the required field is part of the appropriate content types.
 *
 * NB: not using features to avoid dependency problems with other optional
 * modules.
 *
 * @param string $field_name
 *   Name of the field you want to ensure exists and has an instance.
 * @param array $content_types
 *   An array of content type names to act on.
 */
function dennis_client_ensure_field($field_name, $content_types = array('article', 'review')) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');

  // Ensure the field is created only if it doesn't exist.
  $field_info = field_info_field($field_name);
  if (is_null($field_info)) {
    if ($field = dennis_client_get_field_definition($field_name)) {
      field_create_field($field);
    }
  }

  // See if the field is part of the required bundles.
  $info = field_info_field_map();
  if (isset($info[$field_name])) {
    foreach ($info[$field_name] as $bundles) {
      // Only interested in nodes.
      if (!isset($bundles['node'])) {
        // Not a node so check the next bundle.
        continue;
      }

      // Remove from $content_types any that already has the field.
      foreach ($bundles['node'] as $node) {
        $index = array_search($node, $content_types);
        if ($index !== FALSE) {
          unset($content_types[$index]);
        }
      }

    }
  }

  // The field is needed if there are any entries left in $content_types.
  foreach ($content_types as $bundle) {
    if ($instance = dennis_client_get_field_instance_definition($field_name, $bundle)) {
      // Check if there is an existing instance of this field on this bundle.
      $prior_instance = field_read_instance($instance['entity_type'], $instance['field_name'], $instance['bundle']);
      if ($prior_instance === FALSE) {
        field_create_instance($instance);
      }
    }
  }

}

/**
 * Get field definition from a field name.
 *
 * Ensures the fuction that defines the field exists. If it does call it and
 * return result.
 *
 * @param string $field_name
 *   Name of the field to check is defined.
 *
 * @return array
 *   Field config definition.
 */
function dennis_client_get_field_definition($field_name) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');
  $field_config_function = 'dennis_client_' . $field_name . '_config';
  if (function_exists($field_config_function)) {
    return call_user_func($field_config_function);
  }
  else {
    watchdog('dennis_client', 'Field definition for %field does not exist.', array('%field' => $field_name));
  }
}

/**
 * Ensures the fuction that defines the field instance exists.
 *
 * @param string $field_name
 *   Name of the field to check is defined.
 *
 * @return array
 *   Field instance config definition.
 */
function dennis_client_get_field_instance_definition($field_name, $bundle) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');
  $field_config_function = 'dennis_client_' . $field_name . '_instance';
  if (function_exists($field_config_function)) {
    return call_user_func($field_config_function, $bundle);
  }
  else {
    watchdog('dennis_client', 'Field instance definition for %field does not exist.', array('%field' => $field_name));
  }
}


/**
 * Helper function to revert to the field config in dennis_client.field.inc.
 *
 * Only updates if the field exists.
 * Use dennis_client_ensure_field() to create it.
 *
 * @param string $field_name
 *   Name of the field to revert.
 *
 * @see dennis_client_ensure_field()
 */
function _dennis_client_revert_field($field_name) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');
  if ($field = dennis_client_get_field_definition($field_name)) {
    field_update_field($field);
  }
}

/**
 * Helper function to revert to the field config in dennis_client.field.inc.
 *
 * Only updates if the field instance exists.
 * Use dennis_client_ensure_field() to create it.
 *
 * @param string $field_name
 *   Name of the field instance to revert.
 * @param string $bundle
 *   Name of the bundle the field instance is a part of.
 */
function _dennis_client_revert_field_instance($field_name, $bundle) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');
  if ($field_config_instance_function = dennis_client_ensure_field_instance_definition($field_name)) {
    $instance = call_user_func($field_config_instance_function, $bundle);
    field_update_instance($instance);
  }
}

/**
 * Implements hook_views_default_views_alter().
 */
function dennis_client_views_default_views_alter(&$views) {
  // Overrides default views
  // NOTE: This hook only works on views that are not overriden
  // To see which views are overriden, run drush vl
  // To revert a view, run drush vr [view name].
  if (isset($views['content_administration'])) {
    $client_filter = &$views['content_administration']->display['default']->display_options['filters']['field_client_tid'];
    /* Filter criterion: Content: Client (field_client) */
    $client_filter['id'] = 'field_client_tid';
    $client_filter['table'] = 'field_data_field_client';
    $client_filter['field'] = 'field_client_tid';
    $client_filter['value'] = '';
    $client_filter['exposed'] = TRUE;
    $client_filter['expose']['operator_id'] = 'field_client_tid_op';
    $client_filter['expose']['label'] = 'Client';
    $client_filter['expose']['operator'] = 'field_client_tid_op';
    $client_filter['expose']['identifier'] = 'field_client_tid';
    $client_filter['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      3 => 0,
      5 => 0,
      6 => 0,
      4 => 0,
    );
    $client_filter['type'] = 'select';
    $client_filter['vocabulary'] = 'clients';

    $content_partnership_filter = &$views['content_administration']->display['default']->display_options['filters']['field_content_partnerships_tid'];
    /* Filter criterion: Content: Content Partnerships (content_partnerships) */
    $content_partnership_filter['id'] = 'field_content_partnerships_tid';
    $content_partnership_filter['table'] = 'field_data_field_content_partnerships';
    $content_partnership_filter['field'] = 'field_content_partnerships_tid';
    $content_partnership_filter['value'] = '';
    $content_partnership_filter['exposed'] = TRUE;
    $content_partnership_filter['expose']['operator_id'] = 'field_content_partnerships_tid_op';
    $content_partnership_filter['expose']['label'] = 'Content Partnerships';
    $content_partnership_filter['expose']['operator'] = 'field_content_partnerships_tid_op';
    $content_partnership_filter['expose']['identifier'] = 'field_content_partnerships_tid';
    $content_partnership_filter['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      3 => 0,
      5 => 0,
      6 => 0,
      4 => 0,
    );
    $content_partnership_filter['type'] = 'select';
    $content_partnership_filter['vocabulary'] = 'content_partnerships';
  }

  // Exclude sponsored content from news.
  $views['xmlsitemap_news']->display['default']->display_options['filters']['field_content_partnerships_tid'] = array(
    'id' => 'field_content_partnerships_tid',
    'table' => 'field_data_field_content_partnerships',
    'field' => 'field_content_partnerships_tid',
    'operator' => 'empty',
    'type' => 'select',
    'vocabulary' => 'content_partnerships',
  );
}

//@todo write help hook explaining the functionalities of dennis client
//@todo update changelog and make file on 7.x

/**
 * Implements hook_node_view().
 */
function dennis_client_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full') {
    // Adding meta tag for googlebot-news.
    if (dennis_client_node_is_sponsored($node)) {
      $element = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'name' => 'googlebot-news',
          'content' => 'noindex',
        ),
      );
      drupal_add_html_head($element, 'googlebot-news');
    }
    // Fire our context plugin when viewing nodes.
    if ($plugin = context_get_plugin('condition', 'context_condition_content_partnerships')) {
      $plugin->execute($node);
    }
  }
}

/**
 * Determine whether the node is sponsored or not.
 *
 * @param object $node
 *   The node object.
 */
function dennis_client_node_is_sponsored($node) {
  $sponsored = FALSE;

  // If sponsored is selected in field_content_partnerships.
  if (!empty($node->field_client)) {
    if (!empty($node->field_content_partnerships)) {
      if (taxonomy_term_load($node->field_content_partnerships[LANGUAGE_NONE][0]['tid'])) {
        $sponsored = TRUE;
      }
    }
  }

  // Give site modules a chance to decide if the node is really sponsored.
  drupal_alter('dennis_client_node_is_sponsored', $sponsored, $node);

  return $sponsored;
}

/**
 * Implements hook_module_implements_alter().
 */
function dennis_client_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'dfp_global_targeting_alter' && isset($implementations['dennis_dfp'])) {
    // Save dennis_client implementation and remove it from the main array.
    $dennis_client_implementation = $implementations['dennis_client'];
    unset($implementations['dennis_client']);
    $updated_implementations = array();
    foreach ($implementations as $key => $val) {
      // Duplicate existing implementations array.
      $updated_implementations[$key] = $val;
      // Append dennis_client straight after dennis_dfp but before any other
      // implementation.
      if ($key == 'dennis_dfp') {
        $updated_implementations['dennis_client'] = $dennis_client_implementation;
      }
    }
    // Setting implementations.
    $implementations = $updated_implementations;
  }
}

/**
 * Implements hook_taxonomy_term_view().
 * @param $term
 * @param $view_mode
 * @param $langcode
 */
function dennis_client_taxonomy_term_view($term, $view_mode, $langcode) {
  // If the user is anonymous and the vocabulary is content_partnerships, then return 404.
  if ($term->vocabulary_machine_name == 'content_partnerships' && $view_mode == 'full' && user_is_anonymous()) {
    drupal_not_found();
  }
}

/**
 * Implements hook_preprocess_HOOK().
 * @param $variables
 */
function dennis_client_preprocess_taxonomy_term(&$variables) {
  if ($variables['view_mode'] == 'content_partnership') {
    $term = $variables['term'];

    // Wrap content with link.
    if (isset($term->field_client_link[LANGUAGE_NONE][0])) {
      $content = render($variables['content']);
      $url = $term->field_client_link[LANGUAGE_NONE][0]['url'];
      $options = array(
        'html' => TRUE,
        'absolute' => TRUE,
        'attributes' => array(
          'target' => '_blank',
          'rel' => 'nofollow',
        ),
      );
      $content = l($content, $url, $options);
      $variables['content'] = array('link' => array('#markup' => $content));
    }
  }
}


/**
 * Implements hook_entity_presave().
 */
function dennis_client_entity_presave($entity, $type) {
  // When field client is empty, clean up field content partnerships too to
  // prevent the node from showing on news feeds.
  if (isset($entity->field_client)) {
    if (!isset($entity->field_client[LANGUAGE_NONE][0]['tid'])) {
      $entity->field_content_partnerships = array();
    }
  }
}

/**
 * Implements hook_form_alter().
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function dennis_client_form_alter(&$form, &$form_state, $form_id) {
  $form_ids = array(
    'article_node_form',
    'review_node_form',
    'gallery_adv_node_form',
  );
  if (in_array($form_id, $form_ids)) {
    $form['#after_build'][] = '_dennis_client_form_after_build';
    $form['field_content_partnerships']['#states'] =  array(
      'invisible' => array(
        'select[name="field_client[und]"]' => array('value' => '_none'),
      ),
    );
    $form['field_exclude_client_branding']['#states'] =  array(
      'invisible' => array(
        'select[name="field_client[und]"]' => array('value' => '_none'),
      ),
    );
  }
}

/**
 * After build function for field_content_partnerships.
 * @param $form
 * @param $form_state
 */
function _dennis_client_form_after_build($form, &$form_state) {
  $form['field_content_partnerships'][LANGUAGE_NONE]['#options']['_none'] = t('Impartial');
  return $form;
}

/**
 * Implements hook_block_info().
 */
function dennis_client_block_info() {
  $blocks['content_partnerships_block'] = array(
    'info' => t('Content partnerships block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_entity_info_alter()
 */
function dennis_client_entity_info_alter(&$entity_info) {
  // New node view mode.
  $entity_info['taxonomy_term']['view modes']['content_partnership'] = array(
    'label' => t('Content Partnership'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_block_view().
 */
function dennis_client_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'content_partnerships_block':
      $node = menu_get_object();
      if (isset($node->nid) && is_numeric($node->nid)) {
        $wrapper = entity_metadata_wrapper('node', $node);
        if ($term = $wrapper->field_client->value()) {
          $block['subject'] = '';
          $block['content'] = taxonomy_term_view($term, 'content_partnership', $node->language);
        }
      }

      break;
  }

  return $block;
}

/**
 * Implements hook_context_plugins().
 *
 */
function dennis_client_context_plugins() {
  $plugins = array(
    'context_condition_content_partnerships' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'dennis_client') . '/plugins/context',
        'file' => 'context_condition_content_partnerships.inc',
        'class' => 'context_condition_content_partnerships',
        'parent' => 'context_condition',
      ),
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 *
 */
function dennis_client_context_registry() {
  $registry = array(
    'conditions' => array(
      'context_condition_content_partnerships' => array(
        'title' => t('Content partnerships'),
        'description' => t('Condition to enable/disable content partnerships in nodes'),
        'plugin' => 'context_condition_content_partnerships',
      ),
    ),
  );
  return $registry;
}
