<?php
/**
 * @file
 * Code for the Dennis Client feature.
 */

include_once 'dennis_client.features.inc';

/**
 * @file
 * Code for the Dennis Client module.
 */

/**
 * Implements hook_dfp_global_targeting_alter().
 *
 * Adjust the ad tags if the current node, index page is tagged with a
 * "client" taxonomy term.
 * @see https://didev.fogbugz.com/default.asp?20972
 * @see https://didev.fogbugz.com/default.asp?23527
 */
function dennis_client_dfp_global_targeting_alter(&$targeting) {

  // Start point for the $client_page variable.
  $client_page = FALSE;
  $whitelist = array(
    'article',
    'ord',
    'test',
    'live',
  );

  // Get the current page object.
  $item = menu_get_object();

  // Check for a node with content in field_client.
  if ($item && $item->nid && !empty($item->field_client)) {
    if (!empty($item->field_client[LANGUAGE_NONE][0]['taxonomy_term'])) {
      // Use the already loaded term.
      $term = $item->field_client[LANGUAGE_NONE][0]['taxonomy_term'];
    }
    else {
      // Load the term.
      if (isset($item->field_client[LANGUAGE_NONE])) {
        $term = taxonomy_term_load($item->field_client[LANGUAGE_NONE][0]['tid']);
      }
      else {
        $term = FALSE;
      }
    }

    // Sanity check, can't do proper object instance checking in Drupal 7.
    if (!$term) {
      return;
    }

    // Ensure we a referring to our 'client' taxonomy.
    if ($term->vocabulary_machine_name != 'clients') {
      return;
    }

    $client_page = TRUE;
  }
  else {
    // Get the current page object.
    $menu_item = menu_get_item();

    // Add the client key value pair on index pages.
    if (strpos($menu_item['path'], 'taxonomy/term/') !== FALSE && !empty($menu_item['page_arguments'][0])) {
      $term = taxonomy_term_load($menu_item['page_arguments'][0]);
      if (isset($term->vocabulary_machine_name) && $term->vocabulary_machine_name == 'clients') {
        $client_page = TRUE;
      }
    }
  }

  // Check for whitelisted keys and add the client kvp.
  if ($client_page) {

    foreach ($targeting as $index => $entry) {
      if (!in_array($entry['target'], $whitelist)) {
        unset($targeting[$index]);
      }
    }

    $targeting[] = array(
      'target' => 'client',
      'value' => taxonomy_term_title($term),
    );
  }
}

/**
 * Helper to create vocabulary and terms.
 */
function _dennis_client_create_taxonomy() {
  if (!taxonomy_vocabulary_machine_name_load('content_partnerships')) {
    // Create content_partnerships vocabulary.
    $new_vocab = (object) array(
      'name' => 'Content Partnerships',
      'machine_name' => 'content_partnerships',
      'description' => '',
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => '0',
    );
    taxonomy_vocabulary_save($new_vocab);
    drupal_set_message(t('Vocabulary !name has been created.', array('!name' => 'content_partnerships')));
  }
  else {
    drupal_set_message(t('Vocabulary !name already exists.', array('!name' => 'content_partnerships')));
  }

  // Create its terms.
  $vocabulary = taxonomy_vocabulary_machine_name_load('content_partnerships');
  if ($vocabulary->vid) {
    $terms = array(
      'Sponsored' => 0,
      'Advertisement Feature' => 1,
    );
    foreach ($terms as $name => $weight) {
      $term = new stdClass();
      $term->name = $name;
      $term->vid = $vocabulary->vid;
      $term->weight = $weight;
      taxonomy_term_save($term);
    }
  }
}

/**
 * Helper to configure the taxonomy display.
 */
function _dennis_client_set_taxonomy_display() {
  taxonomy_display_save_taxonomy_display('clients', array(
    'term_display_plugin' => 'TaxonomyDisplayTermDisplayHandlerCore',
    'term_display_options' => NULL,
    'associated_display_plugin' => 'TaxonomyDisplayAssociatedDisplayHandlerViews',
    'associated_display_options' => array(
      'view' => 'category_hub',
      'display' => 'default',
    ),
    'breadcrumb_display_plugin' => 'TaxonomyDisplayBreadcrumbDisplayHandlerCore',
    'add_feed' => 1,
  ));
}

/**
 * Helper to migrate and delete field sponsored.
 */
function _dennis_client_migrate_field_sponsored() {
  /**
   * Migrate field_sponsored and delete it.
   */
  // Get the tid for Sponsored.
  $tid = NULL;
  $name = 'content_partnerships';
  $vocabulary = taxonomy_vocabulary_machine_name_load($name);
  $tree = taxonomy_get_tree($vocabulary->vid);
  foreach ($tree as $term) {
    if ($term->name == 'Sponsored') {
      $tid = $term->tid;
    }
  }

  if ($tid) {
    // Migrate legacy data.
    $tables = array(
      'field_data_field_sponsored' => 'field_data_field_content_partnerships',
      'field_revision_field_sponsored' => 'field_revision_field_content_partnerships',
    );
    foreach ($tables as $source_table => $dest_table) {
      $sql = "INSERT INTO " . $dest_table . " (
        entity_type,
        bundle,
        deleted,
        entity_id,
        revision_id,
        language,
        delta,
        field_content_partnerships_tid
      ) SELECT
        legacy.entity_type,
        legacy.bundle,
        legacy.deleted,
        legacy.entity_id,
        legacy.revision_id,
        legacy.language,
        legacy.delta,
        '$tid'
      FROM " . $source_table . " legacy
      LEFT JOIN " . $dest_table . " new ON new.entity_id = legacy.entity_id
      WHERE new.entity_id IS NULL
      AND legacy.field_sponsored_value != '0';";

      $result = db_query($sql);

      if ($result->rowCount() > 0) {
        drupal_set_message(
          t('Copied %rows from %source to %dest.',
            array(
              '%rows' => $result->rowCount(),
              '%source' => $source_table,
              '%dest' => $dest_table,
            )
          )
        );
      }
    }
  }

  // Delete field_sponsored.
  field_delete_field('field_sponsored');
  field_purge_batch(1);

  /**
   * Remove sponsored term from article type.
   */
  $term = taxonomy_get_term_by_name('sponsored', 'article_type');
  $term = array_shift($term);
  if (isset($term)) {
    taxonomy_term_delete($term->tid);
  }
}

/**
 * Ensures the required field is part of the appropriate content types.
 *
 * NB: not using features to avoid dependency problems with other optional
 * modules.
 *
 * @param string $field_name
 *   Name of the field you want to ensure exists and has an instance.
 * @param array $content_types
 *   An array of content type names to act on.
 */
function dennis_client_ensure_field($field_name, $content_types = array('article', 'review')) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');

  // Ensure the field is created only if it doesn't exist.
  $field_info = field_info_field($field_name);
  if (is_null($field_info)) {
    if ($field = dennis_client_get_field_definition($field_name)) {
      field_create_field($field);
    }
  }

  // See if the field is part of the required bundles.
  $info = field_info_field_map();
  if (isset($info[$field_name])) {
    foreach ($info[$field_name] as $bundles) {
      // Only interested in nodes.
      if (!isset($bundles['node'])) {
        // Not a node so check the next bundle.
        continue;
      }

      // Remove from $content_types any that already has the field.
      foreach ($bundles['node'] as $node) {
        $index = array_search($node, $content_types);
        if ($index !== FALSE) {
          unset($content_types[$index]);
        }
      }

    }
  }

  // The field is needed if there are any entries left in $content_types.
  foreach ($content_types as $bundle) {
    if ($instance = dennis_client_get_field_instance_definition($field_name, $bundle)) {
      // Check if there is an existing instance of this field on this bundle.
      $prior_instance = field_read_instance($instance['entity_type'], $instance['field_name'], $instance['bundle']);
      if ($prior_instance === FALSE) {
        field_create_instance($instance);
      }
    }
  }

}

/**
 * Get field definition from a field name.
 *
 * Ensures the fuction that defines the field exists. If it does call it and
 * return result.
 *
 * @param string $field_name
 *   Name of the field to check is defined.
 *
 * @return array
 *   Field config definition.
 */
function dennis_client_get_field_definition($field_name) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');
  $field_config_function = 'dennis_client_' . $field_name . '_config';
  if (function_exists($field_config_function)) {
    return call_user_func($field_config_function);
  }
  else {
    watchdog('dennis_client', 'Field definition for %field does not exist.', array('%field' => $field_name));
  }
}

/**
 * Ensures the fuction that defines the field instance exists.
 *
 * @param string $field_name
 *   Name of the field to check is defined.
 *
 * @return array
 *   Field instance config definition.
 */
function dennis_client_get_field_instance_definition($field_name, $bundle) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');
  $field_config_function = 'dennis_client_' . $field_name . '_instance';
  if (function_exists($field_config_function)) {
    return call_user_func($field_config_function, $bundle);
  }
  else {
    watchdog('dennis_client', 'Field instance definition for %field does not exist.', array('%field' => $field_name));
  }
}

/**
 * Helper function to revert to the field config in dennis_client.field.inc.
 *
 * Only updates if the field exists.
 * Use dennis_client_ensure_field() to create it.
 *
 * @param string $field_name
 *   Name of the field to revert.
 *
 * @see dennis_client_ensure_field()
 */
function _dennis_client_revert_field($field_name) {
  module_load_include('inc', 'dennis_client', 'dennis_client.field');
  if ($field = dennis_client_get_field_definition($field_name)) {
    field_update_field($field);
  }
}

/**
 * Implements hook_views_default_views_alter().
 */
function dennis_client_views_default_views_alter(&$views) {
  // Overrides default views
  // NOTE: This hook only works on views that are not overriden
  // To see which views are overriden, run drush vl
  // To revert a view, run drush vr [view name].
  if (isset($views['content_administration'])) {
    $client_filter = &$views['content_administration']->display['default']->display_options['filters']['field_client_tid'];
    /* Filter criterion: Content: Client (field_client) */
    $client_filter['id'] = 'field_client_tid';
    $client_filter['table'] = 'field_data_field_client';
    $client_filter['field'] = 'field_client_tid';
    $client_filter['value'] = '';
    $client_filter['exposed'] = TRUE;
    $client_filter['expose']['operator_id'] = 'field_client_tid_op';
    $client_filter['expose']['label'] = 'Client';
    $client_filter['expose']['operator'] = 'field_client_tid_op';
    $client_filter['expose']['identifier'] = 'field_client_tid';
    $client_filter['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      3 => 0,
      5 => 0,
      6 => 0,
      4 => 0,
    );
    $client_filter['type'] = 'select';
    $client_filter['vocabulary'] = 'clients';

    $content_partnership_filter = &$views['content_administration']->display['default']->display_options['filters']['field_content_partnerships_tid'];
    /* Filter criterion: Content: Content Partnerships (content_partnerships) */
    $content_partnership_filter['id'] = 'field_content_partnerships_tid';
    $content_partnership_filter['table'] = 'field_data_field_content_partnerships';
    $content_partnership_filter['field'] = 'field_content_partnerships_tid';
    $content_partnership_filter['value'] = '';
    $content_partnership_filter['exposed'] = TRUE;
    $content_partnership_filter['expose']['operator_id'] = 'field_content_partnerships_tid_op';
    $content_partnership_filter['expose']['label'] = 'Content Partnerships';
    $content_partnership_filter['expose']['operator'] = 'field_content_partnerships_tid_op';
    $content_partnership_filter['expose']['identifier'] = 'field_content_partnerships_tid';
    $content_partnership_filter['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      3 => 0,
      5 => 0,
      6 => 0,
      4 => 0,
    );
    $content_partnership_filter['type'] = 'select';
    $content_partnership_filter['vocabulary'] = 'content_partnerships';
  }
}

//@todo write help hook explaining the functionalities of dennis client
//@todo update changelog and make file on 7.x

/**
 * Implements hook_node_view().
 */
function dennis_client_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full') {
    // Adding meta tag for googlebot-news.
    if (dennis_client_node_is_sponsored($node)) {
      $element = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'name' => 'googlebot-news',
          'content' => 'noindex',
        ),
      );
      drupal_add_html_head($element, 'googlebot-news');
    }
    // Fire our context plugin when viewing nodes.
    if ($plugin = context_get_plugin('condition', 'context_condition_content_partnerships')) {
      $plugin->execute($node);
    }
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * Adds the restriction on sponsored checkbox to the query.
 */
function dennis_client_views_query_alter(&$view, &$query) {
  switch ($view->name) {
    case 'xmlsitemap_news':
      // Joining sponsored field to the xmlsitemap_view.
      $join = new views_join();
      $join->table = 'field_data_field_content_partnerships';
      $join->left_table = 'node';
      $join->field = 'entity_id';
      $join->left_field = 'nid';
      $join->type = 'LEFT';
      $join->extra_type = 'OR';
      $query->table_queue['field_data_field_content_partnerships'] = array(
        'table' => 'field_data_field_content_partnerships',
        'alias' => 'field_data_field_content_partnerships',
        'num' => 1,
        'relationship' => 'node',
        'join' => $join,
      );
      $query->where[] = array(
        'conditions' => array(
          array(
            'field' => 'field_data_field_content_partnerships.field_content_partnerships_tid',
            'value' => '',
            'operator' => 'IS NULL',
          )
        ),
        'type' => 'AND',
      );
      break;
  }
}

/**
 * Determine whether the node is sponsored or not.
 *
 * @param object $node
 *   The node object.
 */
function dennis_client_node_is_sponsored($node) {
  $sponsored = FALSE;

  // If sponsored is selected in field_content_partnerships.
  if (!empty($node->field_client)) {
    if (!empty($node->field_content_partnerships)) {
      if (taxonomy_term_load($node->field_content_partnerships[LANGUAGE_NONE][0]['tid'])) {
        $sponsored = TRUE;
      }
    }
  }

  // Give site modules a chance to decide if the node is really sponsored.
  drupal_alter('dennis_client_node_is_sponsored', $sponsored, $node);

  return $sponsored;
}

/**
 * Helper to check whether we should show the content partnership block/rendered entity.
 * @param $node
 */
function dennis_client_show_content_partnership($node) {
  $show = true;
  // Check if the enable checkbox has been selected in the client term.
  if (isset($node->field_client[LANGUAGE_NONE][0]['tid'])) {
    $term = taxonomy_term_load($node->field_client[LANGUAGE_NONE][0]['tid']);
    if (
      isset($term->field_enable_branding_on_nodes[LANGUAGE_NONE][0]['value']) &&
      $term->field_enable_branding_on_nodes[LANGUAGE_NONE][0]['value'] == 0
    ) {
      $show = FALSE;
    }
    else {
      // Check if the exclude checkbox has been selected in the node.
      if (
        isset($node->field_exclude_client_branding[LANGUAGE_NONE][0]['value']) &&
        $node->field_exclude_client_branding[LANGUAGE_NONE][0]['value'] == 1
      ) {
        $show = FALSE;
      }
    }
  }

  return $show;
}

/**
 * Implements hook_module_implements_alter().
 */
function dennis_client_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'dfp_global_targeting_alter' && isset($implementations['dennis_dfp'])) {
    // Save dennis_client implementation and remove it from the main array.
    $dennis_client_implementation = $implementations['dennis_client'];
    unset($implementations['dennis_client']);
    $updated_implementations = array();
    foreach ($implementations as $key => $val) {
      // Duplicate existing implementations array.
      $updated_implementations[$key] = $val;
      // Append dennis_client straight after dennis_dfp but before any other
      // implementation.
      if ($key == 'dennis_dfp') {
        $updated_implementations['dennis_client'] = $dennis_client_implementation;
      }
    }
    // Setting implementations.
    $implementations = $updated_implementations;
  }
}

/**
 * Implements hook_taxonomy_term_view().
 * @param $term
 * @param $view_mode
 * @param $langcode
 */
function dennis_client_taxonomy_term_view($term, $view_mode, $langcode) {
  // If the user is anonymous and the vocabulary is content_partnerships, then return 404.
  if ($term->vocabulary_machine_name == 'content_partnerships' && $view_mode == 'full' && user_is_anonymous()) {
    drupal_not_found();
  }
}

/**
 * Implements hook_preprocess_HOOK().
 * @param $variables
 */
function dennis_client_preprocess_taxonomy_term(&$variables) {
  if ($variables['view_mode'] == 'content_partnership') {
    $term = $variables['term'];

    // Wrap content with link.
    if (isset($term->field_client_link[LANGUAGE_NONE][0])) {
      $content = render($variables['content']);
      $url = $term->field_client_link[LANGUAGE_NONE][0]['url'];
      $options = array(
        'html' => TRUE,
        'absolute' => TRUE,
        'attributes' => array(
          'target' => '_blank',
          'rel' => 'nofollow',
        ),
      );
      $content = l($content, $url, $options);
      $variables['content'] = array('link' => array('#markup' => $content));
    }
  }
}


/**
 * Implements hook_entity_presave().
 */
function dennis_client_entity_presave($entity, $type) {
  // When field client is empty, clean up field content partnerships too to
  // prevent the node from showing on news feeds.
  if (isset($entity->field_client)) {
    if (!isset($entity->field_client[LANGUAGE_NONE][0]['tid'])) {
      $entity->field_content_partnerships = array();
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function dennis_client_preprocess_node(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['node'] = $variables['elements']['#node'];
  $node = $variables['node'];
  if ($variables['view_mode'] == 'full') {
    // Hide the rendered field client.
    if (!dennis_client_show_content_partnership($node)) {
      if (isset($variables['content']['field_client'])) {
        if ($variables['content']['field_client']['#field_type'] == 'taxonomy_term_reference') {
          //@todo check that the view mode = content_partnership, but the information is not available in the array.
          $variables['content']['field_client']['#access'] = FALSE;
        }
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function dennis_client_form_alter(&$form, &$form_state, $form_id) {
  // Show/hide content partnerships field depending on the value of client.
  if (isset($form['field_client'])
    && isset($form['field_content_partnerships']))
  {
    $form['#after_build'][] = '_dennis_client_form_after_build';
    $form['field_content_partnerships']['#states'] =  array(
      'invisible' => array(
        'select[name="field_client[und]"]' => array('value' => '_none'),
      ),
    );
    $form['field_exclude_client_branding']['#states'] =  array(
      'invisible' => array(
        'select[name="field_client[und]"]' => array('value' => '_none'),
      ),
    );
  }
}

/**
 * After build function for field_content_partnerships.
 * @param $form
 * @param $form_state
 */
function _dennis_client_form_after_build($form, &$form_state) {
  // Change the label of _none.
  $form['field_content_partnerships'][LANGUAGE_NONE]['#options']['_none'] = t('Impartial');

  return $form;
}

/**
 * Implements hook_block_info().
 */
function dennis_client_block_info() {
  $blocks['content_partnerships'] = array(
    'info' => t('Content partnerships'),
    'cache' => DRUPAL_CACHE_CUSTOM,
  );

  return $blocks;
}

/**
 * Implements hook_entity_info_alter()
 */
function dennis_client_entity_info_alter(&$entity_info) {
  // New node view mode.
  $entity_info['taxonomy_term']['view modes']['content_partnership'] = array(
    'label' => t('Content Partnership'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_block_view().
 */
function dennis_client_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'content_partnerships':
      $node = menu_get_object();
      if (isset($node->nid) && is_numeric($node->nid)) {
        $wrapper = entity_metadata_wrapper('node', $node);

        if ($term = $wrapper->field_client->value()) {
          // Create cid using all arguments.
          $cid_parts = array(
            'block:dennis_client_partnerships',
            $term->tid,
          );

          // Cache per role.
          $cid_parts = array_merge($cid_parts, drupal_render_cid_parts(DRUPAL_CACHE_PER_ROLE));
          $cid = implode(':', $cid_parts);

          if ($cached_block = cache_get($cid, 'cache_block')) {
            $block = $cached_block->data;
          }
          else {
            $block['subject'] = '';
            $term = taxonomy_term_view($term, 'content_partnership', $node->language);
            // Render the term and cache the rendered output.
            $block['content'] = drupal_render($term);

            if (variable_get('block_cache', FALSE)) {
              cache_set($cid, $block, 'cache_block', CACHE_TEMPORARY);
            }
          }
        }
      }

      break;
  }

  return $block;
}

/**
 * Implements hook_context_plugins().
 *
 */
function dennis_client_context_plugins() {
  $plugins = array(
    'context_condition_content_partnerships' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'dennis_client') . '/plugins/context',
        'file' => 'context_condition_content_partnerships.inc',
        'class' => 'context_condition_content_partnerships',
        'parent' => 'context_condition',
      ),
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 *
 */
function dennis_client_context_registry() {
  $registry = array(
    'conditions' => array(
      'context_condition_content_partnerships' => array(
        'title' => t('Content partnerships'),
        'description' => t('Set this context when field Content Partnerships is checked'),
        'plugin' => 'context_condition_content_partnerships',
      ),
    ),
  );
  return $registry;
}

/**
 * Implements template_preprocess_html().
 */
function dennis_client_preprocess_html(&$variables) {
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = menu_get_object();
    if (dennis_client_show_content_partnership($node)) {
      if ($term = taxonomy_term_load($node->field_client[LANGUAGE_NONE][0]['tid'])) {
        $name = strtolower($term->name);
        $variables['classes_array'][] = 'page-' . drupal_clean_css_identifier($name);
        $variables['classes_array'][] = 'tid-' . $term->tid;
      }
    }
  }
}
